### ISSUE TITLE
US - Diseño sitio web

### ISSUE THREAD

**Issue by martinsantaclara** [classroomMisiones/proyecto-fs-grupo2-g2#1]
### #1 – Diseño del sitio web

**COMO** dueño del producto
**NECESITO** que el sitio web tenga un diseño moderno, agradable, sea intuitivo al navegar, fácil de usar también para personas con capacidades diferentes, accesible desde cualquier tipo de dispositivo (computadora de escritorio, notebook, netbook, tablet, celulares, etc)
**PARA** que el visitante del sitio obtenga una experiencia única que lo induzca a registrarse en la aplicación y convertirse en usuario de la misma.

Descripción:
El sitio web debe ser responsive, con un diseño moderno, intuitivo, que cumpla con los criterios de accesibilidad y usabilidad, siguiendo una filosofía de diseño Mobile First (al menos el 80% del tráfico del sitio web va a provenir de teléfonos celulares) que provoque en el visitante una experiencia confortable que lo induzca a convertirse en un usuario de la aplicación con el objetivo final de conseguir una elevada proporción entre visitantes y usuarios efectivos.
La home page debe contar con, al menos, los siguientes enlaces que conduzcan a contenidos como:
•	¿Quiénes Somos?             Breve reseña de la historia de la empresa y sus fundadores.
•	¿Qué es una billetera virtual?              Descripción detallada del producto que se está ofreciendo para que el usuario se interiorice del alcance de sus transacciones a través de la billetera virtual.
•	Beneficios                 En esta sección se describirán las bondades del producto y todas las ventajas que el usuario obtendrá con el uso de la billetera.
•	Contacto                se especificarán todas las formas en que el usuario podrá comunicarse para realizar todo tipo de consultas (formulario, vía telefónica, redes sociales, chat, email, etc)
•	Registración 	          el visitante, a través del ingreso de sus datos, se convierte en  usuario efectivo de la billetera. (mayores detalles en la HU correspondiente).
•	Ingreso		el usuario, previamente registrado, hace login a la aplicación, a través del ingreso de sus credenciales válidas. (mayores detalles en HU correspondiente).

Criterios de aceptación:
El diseñador presentará al dueño del producto diferentes prototipos y éste elegirá el que considere más adecuado de acuerdo a sus expectativas.

Esta HU es de ALTA prioridad y de MEDIANO esfuerzo.
Queda a modo de revisión por parte del equipo, una vez consensuado todo el detalle de la HU, pasará a formar parte del Product Backlog.

**Comment by Tatiana-Urbina** [comment]
**#2 – Registración del Usuario**
**COMO** usuario
**DESEO** registrarme en la aplicación 
**PARA** convertirme en usuario efectivo y poder utilizar todas las funcionalidades de la misma 
En el formulario de registro se requerirán los siguientes datos:
•	Email
•	Contraseña
•	Repetir contraseña
Criterios de aceptación:
El email debe ser sintácticamente correcto, no debe existir otro usuario con ese email ya registrado. 
La contraseña debe ser de al menos 8 caracteres, incluyendo al menos 1 mayúscula, 1 minúscula y 1 número. El valor que ingresa en Repetir contraseña debe ser igual a lo ingresado en Contraseña.
Antes de concluir el proceso de registración, debe responder a 3 preguntas de seguridad, cuyas respuestas serán utilizadas luego para el proceso de Recuperación de contraseña, en caso de requerirlo.
Se enviará al correo electrónico especificado en el formulario de registro un enlace de activación de la cuenta; una vez recibida la respuesta a dicho link, el proceso de registración se da por terminado y el usuario pasa a ser un usuario efectivo de la aplicación.
La información ingresada será almacenada en la base de datos de la aplicación en la tabla de usuarios con la siguiente estructura:
•	idUsuario
•	email
•	password (encriptado)
•	respuesta1
•	respuesta2
•	respuesta3
Esta HU es de ALTA prioridad y de MEDIANO esfuerzo.
Queda a modo de revisión por parte del equipo, una vez consensuado todo el detalle de la HU, pasará a formar parte del Product Backlog.

**Comment by Javiber17** [comment]
Bien, me parece completa la descripción, cubre muchos puntos importantes para el desarrollo de la billetera.
