### ISSUE TITLE
US - Operaciones con la billetera

### ISSUE THREAD

**Issue by Javiber17** [classroomMisiones/proyecto-fs-grupo2-g2#2]
Como: usuario.
Quiero: transferir dinero en pesos a otra cuenta vía CVU
Para: pagar una compra, servicio o cancelar alguna obligación.

El usuario debe conocer la CVU de destino para poder transferir el dinero

 Criterios de aceptación:
El usuario deberá disponer de saldo para poder realizar transferencias bancarias
El saldo debe ser igual o mayor a la cantidad a transferir
El usuario receptor debe tener habilitada su billetera virtual

**Comment by martinsantaclara** [comment]
Javier, el PARA de la HU creo que habría que modificar a, por ejemplo:

PARA pagar una compra o servicio o cancelar alguna obligación.

Dejo la sugerencia al equipo.

**Comment by Javiber17** [comment]
Bien, me parece correcto el aporte. procedo a corregir.
Gracias!!
