### ISSUE TITLE
US-Registro del usuario

### ISSUE THREAD

**Issue by MatiasGonzalez1** [classroomMisiones/proyecto-fs-grupo2-g2#4]
COMO usuario 
DESEO registrarme en la aplicación 
PARA convertirme en usuario efectivo y poder utilizar todas las funcionalidades de la misma 

En el formulario de registro se requerirán los siguientes datos: 
• Email 
• Contraseña 
• Repetir contraseña 

Criterios de aceptación: 

El email debe ser sintácticamente correcto, no debe existir otro usuario con ese email ya registrado. 
La contraseña debe ser de al menos 8 caracteres, incluyendo al menos 1 mayúscula, 1 minúscula y 1 número. 
El valor que ingresa en Repetir contraseña debe ser igual a lo ingresado en Contraseña. 
Antes de concluir el proceso de registración, debe responder a 3 preguntas de seguridad, cuyas respuestas serán utilizadas luego para el proceso de Recuperación de contraseña, en caso de requerirlo. 
Se enviará al correo electrónico especificado en el formulario de registro un enlace de activación de la cuenta; una vez recibida la respuesta a dicho link, el proceso de registración se da por terminado y el usuario pasa a ser un usuario efectivo de la aplicación.

Esta HU es de ALTA prioridad y de MEDIANO esfuerzo. 

Queda a modo de revisión por parte del equipo, una vez consensuado todo el detalle de la HU, pasará a formar parte del Product Backlog.

**Comment by martinsantaclara** [comment]
Matías, no sé si la definición de la estructura de la tabla Usuarios en la base de datos va como parte de la HU o se define una vez que se decida desarrollar la HU cuando se le asigna a un Sprint. Queda para debatir este punto.

**Comment by Javiber17** [comment]
Tenemos que cambiar en el titulo la HU por US, que sería historia de usuario en ingles user story.
